[package]
name = "wif-checksum"
version = "0.1.0"
authors = ["J/A <archer884@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base58 = { git = "https://github.com/archer884/base58" }
sha2 = "0.9.2"
